# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: 
      - main
env:
  TAG_NAME: feature

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run github script
        uses: actions/github-script@v6
        with:
          debug: true
          script: |
            console.log(context.issue);
            console.log(process.env);
            const tag_name = process.env.TAG_NAME
            const ref_val = `ref/tag/${tag_name}`
            console.log(ref_val)
            const refsResponse = await github.request("POST /repos/{owner}/{repo}/git/refs", {
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: `${{ github.sha }}`,
              ref: `ref/tag/${ref_val}`
            });
            
            
            
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
