# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: 
      - main
env:
  TAG_NAME: feature

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Chrome
        shell: bash
        run: |
          sudo apt-get  install chromium-browser
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install npm
        shell: bash
        run: |
          npm install
      - name: run javascript
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context.issue);
            const response = await github.request("POST /repos/{owner}/{repo}/issues", {
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "Hello",
              body: "I created this issue using Octokit!",
            });
            
            console.log(response)
            const tag_name = ${{ env.TAG_NAME }}
            
            const refsResponse = await github.request("POST /repos/{owner}/{repo}/git/refs", {
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `ref/tag/${{ env.TAG_NAME }}`,
              sha: ${{ github.sha }},
            });
            
            console.log(refsResponse)
           

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
