# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: 
      - main
env:
  TAG_NAME: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Run github script
        uses: actions/github-script@v6
        with:
          debug: true
          script: |
            const response = await github.request("POST /repos/{owner}/{repo}/git/tags", {
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: 'v0.0.1',
                message: 'initial version',
                object: `${{ github.sha }}`,
                type: 'commit',
                tagger: {
                  name: 'Chandra Sekhar',
                  email: 'csreddy.512@gmail.com',
                  date: '2022-12-17T14:53:35-07:00'
                }
            });
            
            console.log(response)
            
            const release = await github.request('POST /repos/{owner}/{repo}/releases', {
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag_name: 'v1.0.0',
                target_commitish: 'master',
                name: 'v1.0.0',
                body: 'Description of the release',
                draft: false,
                prerelease: false,
                generate_release_notes: false
              })
            
            console.log(release)
